<a href="https://colab.research.google.com/github/Ajinmt/Data-Mining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv("kesehatan.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [12]:
print (x)

[[1 58.0 'Perempuan' 152.0 196.0 'Tidak']
 [2 71.0 'Perempuan' 101.0 211.0 'Tidak']
 [3 48.0 'Laki-laki' 129.0 200.0 'Tidak']
 [4 nan 'Perempuan' 137.0 204.0 'Ya']
 [5 62.0 'Laki-laki' 101.0 213.0 'Ya']
 [6 27.0 'Perempuan' 163.0 152.0 'Tidak']
 [7 40.0 'Laki-laki' 159.0 200.0 'Tidak']
 [8 58.0 'Perempuan' 120.0 156.0 'Tidak']
 [9 77.0 'Laki-laki' 132.0 170.0 'Tidak']
 [10 38.0 'Laki-laki' 175.0 222.0 'Tidak']
 [11 42.0 'Perempuan' nan 188.0 'Tidak']
 [12 30.0 'Laki-laki' 121.0 nan 'Tidak']
 [13 30.0 'Perempuan' 148.0 153.0 'Tidak']
 [14 43.0 'Perempuan' 158.0 238.0 'Ya']
 [15 72.0 'Perempuan' nan 209.0 'Tidak']
 [16 55.0 'Perempuan' 159.0 nan 'Ya']
 [17 59.0 'Perempuan' 179.0 158.0 'Tidak']
 [18 43.0 'Perempuan' 114.0 239.0 'Tidak']
 [19 nan 'Perempuan' 161.0 202.0 'Ya']
 [20 41.0 'Perempuan' 161.0 151.0 'Tidak']]


In [13]:
print (y)

['Sehat' 'Sakit' 'Sakit' 'Sehat' 'Sakit' 'Sehat' 'Sakit' 'Sehat' 'Sehat'
 'Sakit' 'Sakit' 'Sehat' 'Sakit' 'Sakit' 'Sakit' 'Sehat' 'Sehat' 'Sehat'
 'Sehat' 'Sehat']


In [79]:
from sklearn.impute import SimpleImputer
def impute_data_sequential(dataset):
    x_numerical = dataset.iloc[:, [ 1, 3, 4]].values
    x_categorical = dataset.iloc[:, [0, 2, 5]].values

    imputer_numerical = SimpleImputer(strategy='mean')
    x_numerical = imputer_numerical.fit_transform(x_numerical)

    imputer_categorical = SimpleImputer(strategy='most_frequent')
    x_categorical = imputer_categorical.fit_transform(x_categorical)

    x = np.hstack((x_categorical, x_numerical))

    return x


Untuk kolom numerik seperti Age, BloodPresure, Cholesterol (1,3,4) menggunakan strategi mean

Untuk kolom kategorial seperti Gender, Smoker, DiseaseStatus (2,5,6) menggunakan strategi most frequent

indeks ke 0 adalah PatientID

In [80]:
x = impute_data_sequential(dataset)

In [81]:
print (x)

[[1 'Perempuan' 'Tidak' 58.0 152.0 196.0]
 [2 'Perempuan' 'Tidak' 71.0 101.0 211.0]
 [3 'Laki-laki' 'Tidak' 48.0 129.0 200.0]
 [4 'Perempuan' 'Ya' 49.666666666666664 137.0 204.0]
 [5 'Laki-laki' 'Ya' 62.0 101.0 213.0]
 [6 'Perempuan' 'Tidak' 27.0 163.0 152.0]
 [7 'Laki-laki' 'Tidak' 40.0 159.0 200.0]
 [8 'Perempuan' 'Tidak' 58.0 120.0 156.0]
 [9 'Laki-laki' 'Tidak' 77.0 132.0 170.0]
 [10 'Laki-laki' 'Tidak' 38.0 175.0 222.0]
 [11 'Perempuan' 'Tidak' 42.0 142.77777777777777 188.0]
 [12 'Laki-laki' 'Tidak' 30.0 121.0 192.33333333333334]
 [13 'Perempuan' 'Tidak' 30.0 148.0 153.0]
 [14 'Perempuan' 'Ya' 43.0 158.0 238.0]
 [15 'Perempuan' 'Tidak' 72.0 142.77777777777777 209.0]
 [16 'Perempuan' 'Ya' 55.0 159.0 192.33333333333334]
 [17 'Perempuan' 'Tidak' 59.0 179.0 158.0]
 [18 'Perempuan' 'Tidak' 43.0 114.0 239.0]
 [19 'Perempuan' 'Ya' 49.666666666666664 161.0 202.0]
 [20 'Perempuan' 'Tidak' 41.0 161.0 151.0]]


In [78]:
print (y)

['Sehat' 'Sakit' 'Sakit' 'Sehat' 'Sakit' 'Sehat' 'Sakit' 'Sehat' 'Sehat'
 'Sakit' 'Sakit' 'Sehat' 'Sakit' 'Sakit' 'Sakit' 'Sehat' 'Sehat' 'Sehat'
 'Sehat' 'Sehat']


In [93]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [ 1, 2])],
    remainder='passthrough'
)
x = np.array(ct.fit_transform(x))

In [94]:
print (x)

[[0.0 1.0 1.0 0.0 1 58.0 152.0 196.0]
 [0.0 1.0 1.0 0.0 2 71.0 101.0 211.0]
 [1.0 0.0 1.0 0.0 3 48.0 129.0 200.0]
 [0.0 1.0 0.0 1.0 4 49.666666666666664 137.0 204.0]
 [1.0 0.0 0.0 1.0 5 62.0 101.0 213.0]
 [0.0 1.0 1.0 0.0 6 27.0 163.0 152.0]
 [1.0 0.0 1.0 0.0 7 40.0 159.0 200.0]
 [0.0 1.0 1.0 0.0 8 58.0 120.0 156.0]
 [1.0 0.0 1.0 0.0 9 77.0 132.0 170.0]
 [1.0 0.0 1.0 0.0 10 38.0 175.0 222.0]
 [0.0 1.0 1.0 0.0 11 42.0 142.77777777777777 188.0]
 [1.0 0.0 1.0 0.0 12 30.0 121.0 192.33333333333334]
 [0.0 1.0 1.0 0.0 13 30.0 148.0 153.0]
 [0.0 1.0 0.0 1.0 14 43.0 158.0 238.0]
 [0.0 1.0 1.0 0.0 15 72.0 142.77777777777777 209.0]
 [0.0 1.0 0.0 1.0 16 55.0 159.0 192.33333333333334]
 [0.0 1.0 1.0 0.0 17 59.0 179.0 158.0]
 [0.0 1.0 1.0 0.0 18 43.0 114.0 239.0]
 [0.0 1.0 0.0 1.0 19 49.666666666666664 161.0 202.0]
 [0.0 1.0 1.0 0.0 20 41.0 161.0 151.0]]


In [95]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [96]:
print (y)

[1 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1]


In [97]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [98]:
print (x_train)

[[1.0 0.0 1.0 0.0 3 48.0 129.0 200.0]
 [0.0 1.0 1.0 0.0 15 72.0 142.77777777777777 209.0]
 [1.0 0.0 0.0 1.0 5 62.0 101.0 213.0]
 [0.0 1.0 1.0 0.0 18 43.0 114.0 239.0]
 [0.0 1.0 1.0 0.0 8 58.0 120.0 156.0]
 [0.0 1.0 1.0 0.0 2 71.0 101.0 211.0]
 [0.0 1.0 0.0 1.0 14 43.0 158.0 238.0]
 [0.0 1.0 1.0 0.0 1 58.0 152.0 196.0]
 [0.0 1.0 1.0 0.0 20 41.0 161.0 151.0]
 [0.0 1.0 0.0 1.0 19 49.666666666666664 161.0 202.0]
 [1.0 0.0 1.0 0.0 10 38.0 175.0 222.0]
 [0.0 1.0 0.0 1.0 16 55.0 159.0 192.33333333333334]
 [1.0 0.0 1.0 0.0 9 77.0 132.0 170.0]
 [0.0 1.0 1.0 0.0 13 30.0 148.0 153.0]
 [1.0 0.0 1.0 0.0 12 30.0 121.0 192.33333333333334]
 [0.0 1.0 1.0 0.0 6 27.0 163.0 152.0]]


In [99]:
print (x_test)

[[0.0 1.0 0.0 1.0 4 49.666666666666664 137.0 204.0]
 [0.0 1.0 1.0 0.0 17 59.0 179.0 158.0]
 [1.0 0.0 1.0 0.0 7 40.0 159.0 200.0]
 [0.0 1.0 1.0 0.0 11 42.0 142.77777777777777 188.0]]


In [100]:
print (y_train)

[0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1]


In [101]:
print (y_test)

[1 1 0 0]
